name = "boat-rental-system"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "botes"
database_id = "84cc1b5c-7275-475b-8e21-80d0be92937b"

